### PR TITLE
updated to latest recommened forge

### PR DESCRIPTION
**Pull request by TheTurkeyDev**
fixed errors and code using old, deprecated methods
added waila through gradlew

### CODE REVIEW

**Comment by TheTurkeyDev** [comment]
I forked it mostly to look at and update my mod that depends of this and while doing so I found a few things that should be tweaked/ fixed. Let me know if you have any problems with anything I did.

**Comment by buttilda** [comment]
Looks pretty good apart from the fact that you deleted the Eclipse project files, if you put them back I'll merge it.

Also, if you know how to make the heads render as items properly I'd greatly appreciate a PR. I've no idea how to do it )=

**Comment by TheTurkeyDev** [comment]
Do you just want the .project back? Yeah I can look into later tonight when I get back

**Comment by buttilda** [comment]
And .classpath
Deleting those would mess up my dev environment XD

**Comment by TheTurkeyDev** [comment]
The classpath really shouldn't be tracked as it is meant to be local to just your machine. Also I only ignored the file, It should not remove it from your workspace.

**Comment by buttilda** [comment]
I realise that, but since I never get PRs I never bothered to fix it XD About time I do it...

**Pull request merged**
