### PR TITLE
Added head on clay transforms into statue and some gradle changes to …

### PR DESCRIPTION
**Pull request by TheTurkeyDev**
…make updating slightly easier

### CODE REVIEW

**Comment by TheTurkeyDev** [comment]
Also let me know if you are looking for someone to maintain this project

**Comment by buttilda** [comment]
If you'd like to mantain the project you're absolutely welcome to do. I don't really have the time to do so anymore ):

**Comment by TheTurkeyDev** [comment]
Would be able to add me to the current curse page?

**Comment by buttilda** [comment]
Sure. What's your curse username?

**Comment by TheTurkeyDev** [comment]
Should be just Turkey.

**Pull request merged**
